# Common properties (applies to all profiles)
spring:
  application:
    name: free-dictionary-api
  profiles:
    active: h2  # Default profile
  jpa:
    open-in-view: false

# Change the application port
server:
  port: 8010 

# Default admin user and password
dict_admin_user: admin
dict_admin_password: admin

# Logging configuration
logging:
  level:
    root: INFO # Default log level
    cc.suvankar.dictionaryapi: DEBUG # Specific package log level
  file:
    name: logs/free-dictionary-api.log # Log file location

---
# H2 profile-specific properties
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:file:./cidedb
    # url: jdbc:h2:mem:cidedb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      data-locations:
      - classpath:schema-h2.sql
  h2:
    console:
      enabled: false

---
# SQLite profile-specific properties
spring:
  config:
    activate:
      on-profile: sqlite
  datasource:
    url: jdbc:sqlite:database.sqlite
    driverClassName: org.sqlite.JDBC
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
      data-locations:
      - classpath:schema-sqlite.sql